" Configuration file for vim                                                                                            
set modelines=0 " CVE-2007-2438

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible " Use Vim defaults instead of 100% vi compatibility
set backspace=2 " more powerful backspacing

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup nobackup

" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup nobackup

let skip_defaults_vim=1

" 取消备份
set nobackup
set noswapfile

" 语法高亮
syntax enable

" 显示行号
set number

" 取消换行
set nowrap

" 背景颜色
set background=dark

" 设置缩进
set cindent
set tabstop=4
set expandtab
set shiftwidth=2

" 文件编码
set encoding=utf-8

" 显示光标当前位置
set ruler

" 突出显示当前行
set cursorline

" 左下角显示当前vim 模式
set showmode

" 设置 paste 模式
set paste
